# Generated by Django 4.0.3 on 2022-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
