# Generated by Django 4.0.3 on 2022-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_client_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.AddField(
            model_name='client',
            name='address_city',
            field=models.CharField(default='', max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='address_country',
            field=models.CharField(default='', max_length=50, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='address_neighborhood',
            field=models.CharField(default='', max_length=50, verbose_name='Colonia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='address_state',
            field=models.CharField(default='', max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electronico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='enterprise_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='enterprise_sector',
            field=models.CharField(choices=[('0', 'ADMINISTRACIÓN Y GESTIÓN (OFICINAS Y DESPACHOS)'), ('1', 'AGRICULTURA Y GANADERÍA'), ('2', 'INDUSTRIA ALIMENTARIA'), ('3', 'COMERCIO'), ('4', 'EDUCACIÓN'), ('5', 'FINANZAS Y SEGUROS'), ('6', 'INFORMACIÓN, COMUNICACIÓN Y ARTES GRÁFICAS'), ('7', 'Otro...')], default='', max_length=1, verbose_name='Sector de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='enterprise_size',
            field=models.CharField(choices=[('0', '1 - 10 empleados'), ('1', '11 - 50 empleados'), ('2', '51 - 100 empelados'), ('3', '101 - 200 empleados'), ('4', '201 o más empelados')], default='', max_length=1, verbose_name='Tamaño de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='rfc',
            field=models.CharField(default='', max_length=13, verbose_name='RFC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='subdomain',
            field=models.CharField(default='', max_length=20, verbose_name='Subdominio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
