# Generated by Django 4.0.3 on 2022-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_client_options_client_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_country',
            field=models.CharField(default='México', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subdomain',
            field=models.CharField(max_length=20, unique=True, verbose_name='Subdominio'),
        ),
    ]
