# Generated by Django 4.0.3 on 2022-03-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Aplicacion', 'verbose_name_plural': 'Aplicaciones'},
        ),
    ]
