# Generated by Django 4.0.3 on 2022-03-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_client_options_client_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estatus', models.BooleanField(verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Clients_Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(verbose_name='Activo')),
                ('expiration_date', models.DateField(verbose_name='Fecha de expiración')),
                ('ip_server', models.CharField(max_length=20, verbose_name='Dirección IP del servidor')),
                ('server_access', models.CharField(max_length=255, verbose_name='Credenciales de acceso')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.client')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.license')),
            ],
        ),
    ]
