# Generated by Django 4.0.3 on 2022-03-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_alter_application_options'),
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients_licenses',
            options={'verbose_name': 'Licenciamiento'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Licencia'},
        ),
        migrations.AddField(
            model_name='license',
            name='applications',
            field=models.ManyToManyField(to='aplicaciones.application'),
        ),
    ]
