# Generated by Django 4.0.3 on 2022-03-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_alter_clients_licenses_options_alter_license_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_licenses',
            name='estatus',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='license',
            name='estatus',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
